on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types:
      - opened
      - synchronize
      - labeled
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
jobs:
  chromatic:
    runs-on: ubuntu-24.04-arm
    # Run Chromatic only if `run_chromatic` label has been applied or we're
    # pushing to `main`.
    if: contains(github.event.pull_request.labels.*.name, 'run_chromatic')  ||  github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          # See https://www.chromatic.com/docs/github-actions/#recommended-configuration-for-build-events
          ref: ${{ github.event.pull_request.head.ref }}
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}
      - name: Setup pnpm - Stand Component Library
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Setup Node.js - Stand Component Library
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Build Storybook - Stand Component Library
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm run build-storybook

      - name: Chromatic - Stand Component Library
        uses: chromaui/action@4cc98810d00b34b8f9e89d454d64a8ac3d088340 # v18.7.1
        with:
          projectToken: ${{ secrets.STAND_CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyChanged: true
