name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - changeset-release/main
permissions:
  contents: read
jobs:
  build_stand:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        include:
          - name: Type check
            run: pnpm tsc
          - name: Type check (TypeScript 6)
            run: pnpm tsc6
          - name: Lint
            run: pnpm lint
          - name: Knip
            run: pnpm knip
          - name: Format check
            run: pnpm format:check
          - name: Unit tests
            run: pnpm test
          - name: Build
            run: pnpm run build
          - name: Build style dictionary
            run: pnpm run build-styled
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ${{ matrix.name }}
        run: ${{ matrix.run }}
